Add Contact Form to Portfolio Website
Zeraltz/Portfolio-Website pull request #4
Opened 2022-04-26 22:03 UTC by Zeraltz

## Changes & Additions
- Add contact form as per requirements
- Form types used properly
- Comply with exercise requirements
- Use Formspree to receive form data
- Linters passed properly
- Add comments for clarity
- Follow Figma template to the detail.

2022-04-26 22:15 UTC, youmari requested changes
Hi @Zeraltz @Daf98, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Descriptive readme file 
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 22:15 UTC, youmari commented on index.html
> +      </ul>
- [ ] [OPTIONAL] these are links to your social media so you should add an `<a>`  tag to all and your social media URL

2022-04-26 22:15 UTC, youmari commented on index.html
> +      <button type="submit" class="main-button">Get in touch</button>
please try to stick to design by implementing the button effect on hover and on pressed as in the Figma design 
![image](https://user-images.githubusercontent.com/61790587/165401317-c4fcd354-28e3-478a-982e-3ef54d499f40.png)

2022-04-27 14:56 UTC, m05e5 approved these changes
# Hi @Zeraltz , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 17:02 UTC, merged