Create and style desktop version of the website
Zeraltz/Portfolio-Website pull request #5
Opened 2022-04-28 22:58 UTC by Zeraltz

## Changes
- Create and style desktop version
- Create Media queries for 768px and up
- Create Media queries for 1600px and up
- Add new divs and new grids to make it easier to style

##Visualization recommended settings
- Please visualize it at 1440px, since this is the size of the FIGMA template and therefore, its the way it looks the most similar

2022-04-28 23:26 UTC, youmari requested changes
Hi @Zeraltz , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ No linter errors
✔️ Descriptive Readme

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 23:26 UTC, youmari commented on index.html
> +      </div>
you have a gap in 800px widescreen, I suggest fixing that so your portfolio will display on any device smoothly
![image](https://user-images.githubusercontent.com/61790587/165862634-958b790f-5ecb-45b6-9c46-6e7d2b477a20.png)

2022-04-28 23:26 UTC, youmari commented on index.html
> +      </div>
Your headline section doesn't look as the one the Figma Design I see you are using the `height: 100vh;` that cause this please try to adjust the style in order that you page look the same as the one in the Figma design 

- [ ] Yours
![image](https://user-images.githubusercontent.com/61790587/165862877-e393cf40-108e-44e9-94ca-cac543195d25.png)

- [ ] Figma design 
![image](https://user-images.githubusercontent.com/61790587/165862908-50c19294-f2d0-4746-a3a1-0f16ee7bc5f7.png)

2022-04-28 23:26 UTC, youmari commented on index.html
also, you forgot to include the illustrations in the headline section I suggest doing that 
![image](https://user-images.githubusercontent.com/61790587/165862990-f7cd9888-77a4-41a4-a711-edd808c313a4.png)

2022-04-28 23:26 UTC, youmari commented on index.html
> +        </div>
Kindly try to fix your image src link right now I can't see them you can fix them by adding a dot before the slash and use the right path
![image](https://user-images.githubusercontent.com/61790587/165863179-f4aeb5c7-c312-4961-a6e8-c7236b2b9450.png)

2022-04-29 16:09 UTC, AmaduKamara approved these changes
# Status: Approved 🟢🟢🟢 

Hi @Zeraltz,

Good job implementing all the changes asked by the previous reviewer. The project looks great 💪💪💪

![ClappingLeonardoDicaprioGIF (2)](https://user-images.githubusercontent.com/50941074/165982360-7098fe8e-1fed-45cc-8106-26036f8129f6.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-29 16:41 UTC, merged